
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: check-yaml
    args: [--unsafe]
  - id: check-merge-conflict
  - id: check-symlinks
  - id: mixed-line-ending

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.241
  hooks:
  - id: ruff
