name: Automated tests & code coverage

on: [push, pull_request]

jobs:

  code-qa-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest] #, macos-latest, windows-latest]
      fail-fast: False

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[develop]"
    - uses: pre-commit/action@v3.0.0
    - name: Run tests
      if: success() || failure()  # Run this step even if the linting step fails
      run: |
        # -rA displays the captured output for all tests after they're run
        # See the docs: https://doc.pytest.org/en/latest/reference/reference.html#command-line-flags
        pytest -rA tests/
